spring:
  application:
    name: cleanseed

  datasource:
    url: jdbc:h2:mem:cleanseed;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true # Opzionale: rende l'SQL nei log pi√π leggibile

  h2:
    console:
      enabled: true
      path: /h2-console

# Se vuoi cambiare la porta del server (opzionale)
server:
  port: 8080